name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        # uses: matchai/waka-box@master
        uses: sansx/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 707cc3c70b33ab21da41beb9a009e713
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
