name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5dbdf6d66967c471e8db3fc64c8ada65
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
